version: "3"
services:
  httpgatewaycoucou:
    container_name: httpgatewaycoucou
    image: nginx:alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./api/http:/web
    ports:
      - 8080:80
    networks:
      - web
    depends_on:
      - database
      - backendfpm
      - frontendreact
  database:
    container_name: database
    image: mariadb/server
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: hello
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/schemas:/docker-entrypoint-initdb.d
    networks:
      - web
  backendfpm:
    container_name: backendfpm
    build: api/
    environment:
      DB_HOST: database
      DB_USER: user
      DB_PASS: password
      DB_NAME: todo
    volumes:
      - ./api/http:/web
    networks:
      - web
  frontendreact:
    container_name: frontendreact
    build: frontend/
    environment:
      API_URL: backendfpm
    ports:
      - 80:3000
    networks:
      - web
    depends_on: 
      - backendfpm
networks:
  web:
    driver: bridge